eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090
spring:
  application:
    name: product
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/productdb
    username: devuser
    password: devpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

management:
  tracing:
    sampling:
      probability: 1.0